### ISSUE TITLE
Examples not building on Linux

### ISSUE THREAD

**Issue by FarLanderCraft** [GValiente/butano#1]
![image](https://user-images.githubusercontent.com/67613281/98891055-59b3fa80-246b-11eb-806d-ea3d3808e10d.png)
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: btn_hw_audio.o: in function `btn::hw::audio::init()':
/home/farlandercraft/2Drive/GBADev/butano/butano/hw/src/btn_hw_audio.cpp:139: undefined reference to `_btn_audio_soundbank_bin'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/gba_rules:25: /home/farlandercraft/2Drive/GBADev/butano/tests/tests.elf] Error 1
make: *** [/home/farlandercraft/2Drive/GBADev/butano/butano/butano.mak:137: build] Error 2

I get an error saying "butano/hw/src/btn_hw_audio.cpp:139: undefined reference to `_btn_audio_soundbank_bin`"
every time I try to build any of the examples, or Butano Fighter. Please fix this soon ;-; ...

(Arch Linux, Kernel 5.9.1-arch1-1, gcc version 10.2.0.)

**Comment by GValiente** [comment]
Hi, 

I have been able to build some examples, the tests and Butano Fighter on a fresh installation of Ubuntu 20.

Have you been able to build some of the devkitARM examples?

**Comment by FarLanderCraft** [comment]
It seems that most of the devkitARM examples build, but a few don't XD .
Though I'm not 100% certain that the causes are similar, they may be. (I'm very new at C and C++, so I have a hard time telling what exactly the errors mean.)

**Comment by FarLanderCraft** [comment]
Update:
I got the examples for DevKitARM to build correctly (I was missing a bin file), but butano's examples throw the same error.

**Comment by GValiente** [comment]
Good!

Could you do a full rebuild of a butano project (`make clean` and then `make -j4`) and if it keeps failing post the **full** log here, please?

**Comment by FarLanderCraft** [comment]
I forgot to say about five hours ago that when I built it in an Ubuntu VM it worked, so it may actually be a problem with my system's compiler for some reason (likely a change I made), so a reinstall would fix it.
Sorry for wasting your time XD .

**Comment by FarLanderCraft** [comment]
Reinstalling GCC did work, it built...
Sorry again ;-; .
I dum at C++ stuff.

**Comment by GValiente** [comment]
Hey, you are not the first one with compiler issues :)

I'm glad it worked. Thanks for looking at it (and keep trying until it worked).
