### ISSUE TITLE
Is there any more convenient way for me to convert mod or it audio?

### ISSUE THREAD

**Issue by zxsean** [GValiente/butano#12]
Is there any more convenient way for me to convert mod or it audio?

**Comment by zxsean** [comment]
I try to use 
![image](https://user-images.githubusercontent.com/7285186/132990499-f3f2a094-d94b-48fb-8c81-ac0189e6dfec.png)
to convert WAV to it. I have successfully converted it, but the final it audio has intermittent problems.

**Comment by GValiente** [comment]
[Maxmod](https://maxmod.devkitpro.org/) (the library used by Butano for audio stuff) doesn't seem to support audio samples longer than 6 seconds or so, so if you don't split the source wav in small samples it is not going to work with Maxmod.

If you are able to make it work please let me know :)

**Comment by zxsean** [comment]
!!! Now I know why my BGM only 6s....   by the way, can I create an array and put XX 6s BGM in this array then loop this array?

**Comment by GValiente** [comment]
I guess you can, but I think splitting the source wav in small pieces and making a mod file with them is going to be better for avoiding sync issues.

**Comment by zxsean** [comment]
Is there any plan to support wav BGM?

**Comment by GValiente** [comment]
Ask to Maxmod devs :)

**Comment by zxsean** [comment]
lol~~ Maxmod It seems that it hasn't been updated for a long time?

**Comment by GValiente** [comment]
Yeah, it seems so.

**Comment by zxsean** [comment]
I find that BPCore-Engine has a good way to play the WAV BGM.

**Comment by GValiente** [comment]
Sorry, but for now there's no plans for supporting more audio libries.

**Comment by zxsean** [comment]
ok
