### ISSUE TITLE
[Q] use instance method syntax

### ISSUE THREAD

**Issue by eadmaster** [GValiente/butano#13]
For better readability and quicker typing, is it possible to invoke the library methods like this?
````
    bn.core.init();
    bn.regular_bg_ptr background = bn.regular_bg_items.gba.create_bg(0, 0);
    bn.sprite_ptr up_sprite = bn.sprite_items.up_button.create_sprite(-63, -47);
...
````

**Comment by GValiente** [comment]
AFAIK C++ doesn't let to refer to namespaces like that.

**Comment by eadmaster** [comment]
what about adding a static class that references all the functions in the `bn` namespace, so the dot operator could be used?

**Comment by felixjones** [comment]
> what about adding a static class that references all the functions in the `bn` namespace, so the dot operator could be used?

Always tempting (indeed I used to do this in my own code) but then you've got a static reference to something hanging around in ROM/WRAM that requires a unique address and has size of at least 1 byte. IMO not worth it for the sake of achieving syntactic sugar in defiance of C++ conventions.

Also it wastes register 0 for the `this` pointer for `__thiscall`.

It's very subjective if obscuring functions behind a fake guise of member call syntax is actually more readable or not.

**Comment by GValiente** [comment]
I mean, what's wrong with the `::` operator?

I think it makes the code more readable since it allows to distinguish a namespace from an object.

**Comment by eadmaster** [comment]
Most scripting languages use the dot operator for namespace addressing, so for me it is also a matter or habit in addition to readability.

Btw if this is going to have a performance penality then i'm reconsidering.
