### ISSUE TITLE
Examples not building on MacOS

### ISSUE THREAD

**Issue by AgustinMachiavello** [GValiente/butano#14]
Hi :)

I was trying to build the example projects but every single time I get the following error:
`error: array subscript value '17' is outside the bounds of array type 'char [17]'`

Any ideas? 
I'm new with C/C++ and I thought this could be a fun place to start.

I'm on MacOS Monterrey 12.0.1 

Thanks!!!

Here is a more detailed error log:
`/Users/agustinmachiavello/softwareprojects/butano/butano/include/bn_span.h:480:9:   in 'constexpr' expansion of '_bn::assert::file_name<10>(((const char*)"/Users/agustinmachiavello/softwareprojects/butano/butano/include/bn_span.h"))'
/Users/agustinmachiavello/softwareprojects/butano/butano/include/bn_assert.h:171:35: error: array subscript value '17' is outside the bounds of array type 'char [17]'
make[2]: *** [common_stats.o] Error 1
make[2]: *** [main.o] Error 1
make[1]: *** [build] Error 2
make: *** [all] Error 2`

**Comment by GValiente** [comment]
Hi, 

I can't reproduce that error with the latest versions of Butano and devkitARM.

Do you have the latest version of both projects?

What example are you trying to build?

**Comment by AgustinMachiavello** [comment]
Thanks for the quick reply.

I was trying to build the _text_ example project, but the same error pops up with all the others so I'm thinking it's more like a set-up related problem.

I've just downloaded Butano 8.6.0 version and for I'm using devkitPRO 1.0.2.

I'm not sure how to get the devkit version it self, but reinstalling it via Pacman showed the following results: 
`armv4t-pkg-config-0.28-1  devkitARM-r56-4  devkitARM-gdb-10.2-1
              devkitarm-cmake-1.0.0-4  devkitarm-crtls-1.1.1-1
              gba-examples-20190122-1  gba-tools-1.2.0-1  general-tools-1.2.0-2
              grit-0.8.16-1  libfat-gba-1.1.5-1  libgba-0.5.2-2
              libtonc-1.4.3-3  maxmod-gba-1.0.14-1  mmutil-1.9.1-1
              pkg-config-0.29.2-1`

**Comment by GValiente** [comment]
I have GCC 11 on my machine, so it should be a devkitARM install issue.

Try reinstalling it using [this guide](https://devkitpro.org/wiki/Getting_Started).

**Comment by AgustinMachiavello** [comment]
Found the issue! :)

I just edited the line 156 inside `bn_assert.h` like this:

FROM:
`alignas(int) char characters[Size < 17 ? 17 : Size];`

TO:
`alignas(int) char characters[Size < 170 ? 170 : Size];`

I just set 170 as a random number tho. I'm not sure why it was set to 17.

Do you want me to open a PR or something?

**Comment by GValiente** [comment]
Sorry, but do you still have that issue with the latest version of devkitARM?

**Comment by AgustinMachiavello** [comment]
Yeah. I reinstalled devkitARM, Xcode tools, and even checked my gcc version but nothing really worked. The same error message kept appearing after all that.

In my case, the examples did not compile due to a code error (the one described on my previous comment), not really a set-up error.

I even got it running on VisualBoy Advanced now!

**Comment by GValiente** [comment]
Thanks.

Could you find the lowest value that works with you machine?

**Comment by AgustinMachiavello** [comment]
18

Now the line looks like this:
`alignas(int) char characters[Size < 18 ? 18 : Size];`

Not sure why tho lol

**Comment by GValiente** [comment]
Great.

Could you try to update Butano to check if it works now?

**Comment by AgustinMachiavello** [comment]
It works!

Just compiled a few examples without a problem.

THANKS :)
