### ISSUE TITLE
3D support?

### ISSUE THREAD

**Issue by Guillermo-Ramirez-Jimenez** [GValiente/butano#16]
Hi,
I was wondering if there are specific resources included intended for 3D development. Something geometrically simple, similar to PSX or Minecraft.
Skeletons, animation controllers and collisions perhaps?
I was inspired by the recent impressive port of OpenLara for GBA. It clearly shows this console is able to manage 3D graphics, even if a lot of optimization is needed.
Thanks in advance.

**Comment by GValiente** [comment]
No, sorry.

**Comment by GValiente** [comment]
Closed due to lack of activity.
