### ISSUE TITLE
Visual Studio Solution

### ISSUE THREAD

**Issue by Manurocker95** [GValiente/butano#2]
Could you provide VS Solution? I'd like to make some tests making a .DLL and creating a Unity Engine Plugin so it can be used directly with the engine

**Comment by GValiente** [comment]
As we talked yesterday, maybe the only sane way to integrate Butano with Unity would be to generate C++ code from it, and for that there's no need for DLLs nor Visual Studio solutions.

If you get some progress related with this, please let me know it!
