### ISSUE TITLE
[Request] Changes in butano repo for supporting BMFont

### ISSUE THREAD

**Issue by laqieer** [GValiente/butano#20]
- [x] https://github.com/GValiente/butano/pull/18/commits/2a539dcd6642e6627beccc9dee85072f363242b4

*Note: this issue is created according to discussion: https://github.com/GValiente/butano/pull/18*

**Comment by GValiente** [comment]
[Done](https://github.com/GValiente/butano/commit/2bd896ce816d1557c253ce017dcdf0892ca26d5b).

**Comment by laqieer** [comment]
Could you please add a link to [BMFont support extension repo](https://github.com/laqieer/gba-free-fonts) in butano documentation?

**Comment by GValiente** [comment]
[Sure](https://github.com/GValiente/butano/commit/4e3e1f3374162b56caef788121e8f5a304a4ee96) :)
