### ISSUE TITLE
bgs/sprites are still *committed to the GBA* after calling `set_visible(false)`?

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#22]
I'm still confused about the docs on `bn::regular_bg_ptr::set_visible(bool)`.

https://gvaliente.github.io/butano/classbn_1_1regular__bg__ptr.html#a993fb7c4be866dae3fac01ba36db0ecd
> void set_visible(bool visible)
> **Sets if this regular background must be committed to the GBA or not.**

https://gvaliente.github.io/butano/namespacebn_1_1bgs.html#a5cb214772bcaf49a87011baa6bfbbec4
> int bn::bgs::used_items_count()
> Returns the number of used background items.
> 
> **A background item which is hidden is not committed to the GBA, so there can be more than 4 background items.**

At first glance, I thought calling `bn::regular_bg_ptr::set_visible(false)` on some bgs would allow me to *deallocate* them,
so that I can have more than 4 unique regular bgs, but **only up to 4 of them can be set as visible.**

But clearly this is not how it works, as this code fails to do that.

```cpp
#include "bn_bgs.h"
#include "bn_core.h"
#include "bn_log.h"
#include "bn_regular_bg_ptr.h"
#include "bn_vector.h"
// graphics/blue.bmp
#include "bn_regular_bg_items_blue.h"

int main() {
    bn::core::init();
    bn::vector<bn::regular_bg_ptr, 5> bgs;
    for (int i = 0; i < 5; ++i) {
        bgs.push_back(bn::regular_bg_items::blue.create_bg(0, 0));
        // set_visible(false) for every single regular bg
        bgs.back().set_visible(false);
        BN_LOG("used_bg=", bn::bgs::used_items_count(), ", available_bg=", bn::bgs::available_items_count());
    }
    while (true)
        bn::core::update();
}
```

![test-0](https://user-images.githubusercontent.com/34793045/183017286-d150072b-63d1-4f6b-b292-8ddb692697ff.png)

```
[WARN] GBA Debug:	used_bg=1, available_bg=3
[WARN] GBA Debug:	used_bg=2, available_bg=2
[WARN] GBA Debug:	used_bg=3, available_bg=1
[WARN] GBA Debug:	used_bg=4, available_bg=0
```

Same goes for affine bgs and sprites.

Does *"committed to the GBA"* mean something different?
Or am I missing something else?

**Comment by GValiente** [comment]
GBA has 4 regular backgrounds, it can't show more than that.

Butano has "virtual" background entities, that are not committed to the GBA unless the background is visible, so you can have more than 4 "virtual" backgrounds.

But by default the maximum number of "virtual" backgrounds is also 4. If you want to increase that limit, you must overwrite this config value: https://gvaliente.github.io/butano/group__bg.html#ga9b4566bdd05aaf52b482da454f9a60d1

**Comment by copyrat90** [comment]
Thanks a lot for quick reply!
I didn't thought there would be a limit for the *virtual* background entities.
Maybe the `No more available BGs` message on the screenshot could rather be `No more available "virtual" BGs`?

* * *

I'm leaving this note for future readers.
You can add `-DBN_CFG_BGS_MAX_ITEMS=8` on [`USERFLAGS := ` on Makefile](https://github.com/GValiente/butano/blob/921f75ffb160442836248d5edabcb76d2134aa0f/template/Makefile#L40) to override this value.
And there's also this [`BN_CFG_SPRITES_MAX_ITEMS` config value for sprites](https://gvaliente.github.io/butano/group__sprite.html#gad9ac6fa1ea291dd3dcc71212b682b737)
