### ISSUE TITLE
It would be nice to be able to change palette colors

### ISSUE THREAD

**Issue by ultrasuperpingu** [GValiente/butano#26]
I'd like to switch smoothly between 2 color palette. It does not seams to be possible.
Just to try, I made "bn_palettes_manager.h" and "palette_bank.h" public and I use `bn::palettes_manager::bg_palettes_bank().set_colors(0,colors);`
It seams to work, but it would be nice to be able to do that with vanilla code.

**Comment by GValiente** [comment]
`bn::palettes_manager` namespace is part of the private API, you should avoid using it.

You can change the colors of any background palette with [bn::bg_palette_ptr::set_colors](https://gvaliente.github.io/butano/classbn_1_1bg__palette__ptr.html#a86cb251ddd52e6ee5f69fbd30543cb2a).

**Comment by ultrasuperpingu** [comment]
Sorry, I'm stupid, I saw it was possible to change the palette_item but then looked for a way to change the colors of the palette items. I didn't realize, I just had to instanciate a new one :(
I guess you can close this issue.
