### ISSUE TITLE
Discord server invite is invalid

### ISSUE THREAD

**Issue by EliasWolf-Br** [GValiente/butano#27]
The discord.io/gbadev (discord invite) is not working.

**Comment by GValiente** [comment]
It works for me.

It seems you have been banned, maybe the invite is not working because of that?

**Comment by EliasWolf-Br** [comment]
> It works for me.
> 
> It seems you have been banned, maybe the invite is not working because of that?

Is not It, can you send me another invite?

**Comment by EliasWolf-Br** [comment]
> Sorry, but the gbadev discord link shouldn't work for you since you have been banned.

Mas eu não fui banido, eu sair de lá.
