### ISSUE TITLE
Provide template specialization for `bn::array<T, 0>`(empty array) ?

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#32]
# Requested feature
Provide a template specialization for `bn::array<T, 0>` (Zero-sized, empty array).

# Use case
In my current game, I'm generating `constexpr MTilemap` instances to store meta-tilemap information in ROM.
To do this, I'm storing bunch of `bn::array<SpawnPointType, Count>` instances like below:
```cpp
// Meta-tilemap struct to hard-coded in ROM.
// The instance of this class will be generated with auto-tilemap generation Python script.
template <int MWidth, int MHeight, int MobCount, int ItemCount, int MCellDecoCount, int DecoCount>
struct MTilemap : MTilemapBase
{
private:
    const bn::array<MobSpawnPoint, MobCount> _mobSpawnPoints;
    const bn::array<ItemSpawnPoint, ItemCount> _itemSpawnPoints;
    const bn::array<MCellDecoSpawnPoint, MCellDecoCount> _mCellDecoSpawnPoints;
    const bn::array<DecoSpawnPoint, DecoCount> _decoSpawnPoints;
    const bn::array<MTileIndex, MWidth * MHeight> _board;
    ...
};
```

But if any of these `Count` template arguments turns out to be zero, this `MTilemap` struct won't work.
Because `bn::array` doesn't support zero-sized arrays.
https://github.com/GValiente/butano/blob/bc9d142a09034ed5433f07c949c058708ae0707e/butano/include/bn_array.h#L25-L28

I could make a custom wrapper around `bn::array` to deal with empty array, but it would be nice if it is supported directly on `bn::array`.
So, could you please provide a template specialization for the `bn::array<Type, 0>`, [like the `std::array` does?](https://en.cppreference.com/w/cpp/container/array)

**Comment by GValiente** [comment]
https://github.com/GValiente/butano/commit/03f6edcf069d6462f7eb07c60dcc699b41802db9

**Comment by copyrat90** [comment]
Thanks a lot!
You've done it so quick so I haven't got the actual compilation error for this, haha.
