### ISSUE TITLE
Provide an option to export instruments on `s3m2gbt`

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#34]
You can [export custom waveform on `s3m2gbt`](https://github.com/GValiente/butano/tree/03f6edcf069d6462f7eb07c60dcc699b41802db9/butano/tools/s3m2gbt#samples).

> You are allowed to replace the samples of the channel 3. If the resulting sample is exactly 32 or 64 samples long, you can pass the --instruments flag to s3m2gbt and it will export all valid instruments along the patterns of your song. They will replace the default instruments of GBT Player for the duration of the song.

But looks like Butano doesn't provide any option to enable it.

Related closed PR: #33

**Comment by GValiente** [comment]
You now can specify dmg music import options with a json file.

Check [this guide](https://gvaliente.github.io/butano/import.html#import_dmg_music) and the `dmg_audio` example.

**Comment by copyrat90** [comment]
Thanks!
