### ISSUE TITLE
Provide `value_template_actions`, but storing `const Value&` instead?

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#37]
I tried to add `value_template_actions` to my own `Entity` class, but it seems that every action template copies it by value.

https://github.com/GValiente/butano/blob/10f3688ccd9950e1ecf1995594544a4e84d2337e/butano/include/bn_value_template_actions.h#L94-L95

This effectively copies the `Entity`, thus there's a duplicated copy of instances in the game.
So this template would work only if the copy of `Value` shares the members with the original, but it's generally not the case in my opinion.
And also, my `Entity` is actually an abstract class, so I can't use this at all.

I could easily copy these and change it to store `const Value&` instead, but it would be nice if they are in the Butano directly.

**Comment by GValiente** [comment]
Actions taking ownership of the affected value is by design, and changing that would break lots of old code.

As you said, you always can create your own actions that don't copy the affected value.

**Comment by copyrat90** [comment]
Ok, I'll do that then.

**Comment by GValiente** [comment]
Maybe you can reusing existing actions by using reference wrappers: https://en.cppreference.com/w/cpp/utility/functional/reference_wrapper

**Comment by copyrat90** [comment]
> Maybe you can reusing existing actions by using reference wrappers: https://en.cppreference.com/w/cpp/utility/functional/reference_wrapper

Nice, it works perfectly with `std::reference_wrapper`.  Thanks a lot!
