### ISSUE TITLE
Allow the random value to be discarded

### ISSUE THREAD

**Issue by natebot13** [GValiente/butano#40]
https://github.com/GValiente/butano/blob/8d16ff389b8888ecac12da42375d7aeb982fac83/butano/include/bn_random.h#L40

Would like to request that the [[nodiscard]] here be removed as it could be useful to progress the internal state of the RNG while ignoring the return value.

**Comment by copyrat90** [comment]
You can call `bn::random::update()` directly to progress the internal state of the RNG without getting the value.

https://gvaliente.github.io/butano/classbn_1_1random.html#af576b431d31a4cf348dfddf17b5b6526

**Comment by natebot13** [comment]
Ah, I had completely missed that api. Thanks!
