### ISSUE TITLE
Is possible to use 16x16 tiles in Regular backgrounds?

### ISSUE THREAD

**Issue by luismesas** [GValiente/butano#46]
Hi,

I may not be fully understanding how Regular Backgrounds work.

I'm trying to compose a fullscreen screen background composed of 16x16 pixel tiles instead of what looks to be the default of 8x8 pixel tiles.

Is it possible to specify a different tile size?

Thanks

**Comment by GValiente** [comment]
No, only native GBA tile size (8x8) is supported.

**Comment by GValiente** [comment]
Closed due to lack of activity.
