### ISSUE TITLE
[Docs] Same derived class appears 6 times in `bn::igeneric_pool_base`

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#48]
![Screenshot_20230429-113906_Kiwi Browser](https://user-images.githubusercontent.com/34793045/235279822-547646fc-5378-4aaf-85b7-267d7fadf0b6.png)

**Comment by GValiente** [comment]
It seems a [m.css](https://github.com/mosra/m.css) issue, since it doesn't happen when generating regular Doxygen HTML documentation.

**Comment by GValiente** [comment]
Don't know how to avoid it, by the way :)

**Comment by copyrat90** [comment]
Well, in that case, I'll just close this issue, since it's not a big deal.
