### ISSUE TITLE
[Feature Request] Ability to run user-defined code upon failed BN_ASSERT or BN_ERROR?

### ISSUE THREAD

**Issue by SomeRanDev** [GValiente/butano#54]
This might be a bit of a niche request, but it would be nice to have a way to write code that is executed when an assert or error is failed for testing/development purposes. That way developers can log additional diagnostic information.

Of course, one could simply define `BN_ASSERT` or `BN_ERROR` themselves, but it would be nice to not have to copy and paste the existing implementation. 

Perhaps there could be a definable macro placed next to [`_bn::assert::show` and `_bn::assert::show_args`](https://github.com/GValiente/butano/blob/db57c703581ee6ab58d2a591b4c055c46a62c0a7/butano/include/bn_assert.h#L139C35-L139C35) like `BN_CFG_ON_ASSERT_FAIL` and `BN_CFG_ON_ERROR` that the user could define to inject code into the assert (+error)?

**Comment by GValiente** [comment]
You can always make your own assert that does that, no need to update Butano:
```cpp
#define MY_ASSERT(condition, my_code, ...) \
    do \
    { \
        if(bn::is_constant_evaluated()) \
        { \
            assert(condition); \
        } \
        else \
        { \
            if(! (condition)) [[unlikely]] \
            { \
                my_code(); \
                _bn::assert::show_args(#condition, __FILE_NAME__, __func__, __LINE__ __VA_OPT__(, ) __VA_ARGS__); \
            } \
        } \
    } while(false)
```

And then you can use it like this:
```cpp
MY_ASSERT(false, bn::core::update, "wtf");
```

**Comment by SomeRanDev** [comment]
Oh, sorry for the confusion! What I meant the ability to execute the same code once any assert fails or error occurs. This includes existing `BN_ASSERT`s and `BN_ERROR`s already written in the Butano library.

**Comment by GValiente** [comment]
Once an error message is displayed, the engine isn't able to recover (all subsystems are shut down), so you'll probably need to implement your own assert system to allow that.

**Comment by SomeRanDev** [comment]
The intent is not to execute code relying on Butano systems. It would be to log (through `BN_LOG`) custom diagnostics and global information regarding the state of the program before shut down.

**Comment by GValiente** [comment]
To do that, the `MY_ASSERT` macro should be more than enough.

**Comment by GValiente** [comment]
Thinking about it, the custom macro idea would not work for asserts triggered by butano itself. I'll probably add an optional callback to the asserts and such.

**Comment by GValiente** [comment]
This new assert callback should be enough for your use case: https://github.com/GValiente/butano/commit/b1235e64084fec6feda066d1f86f3c102b15394d
