### ISSUE TITLE
DMG music master volume is 25% (too quiet)

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#56]
**Both** GBT Player & VGM Player forgot to set the `REG_SOUNDCNT_H |= SOUNDCNT_H_PSG_VOLUME_100;`
The default volume for DMG is **25%**, that's why DMG music is so quiet compared to Maxmod music.

https://gbadev.net/gbadoc/audio/registers.html#direct-sound-output-control-register
https://gbadev.net/tonc/sndsqr.html#sec-gbasnd

**Comment by copyrat90** [comment]
Lorenzooone in the gbadev Discord says:
> Maxmod sets values related to this in mmMixerInit. So you may want to alter it after the mmInit call.
> Or have a wrapper which takes the value and re-sets it to what it was after mmInit.

**Comment by GValiente** [comment]
GBT Player sets volume to the maximum allowed when it plays a song: https://github.com/GValiente/butano/blob/5253c0444b64ef85655252b871f1c440aba4aa16/butano/hw/3rd_party/gbt-player/src/gbt_player.c#L522

And VGM Player doesn't support volume setup, so Butano can't do anything with that.

**Comment by copyrat90** [comment]
That's a different thing, what `gbt_volume(left, right)` does is setting the relative volume between DMG left & right (`SOUNDCNT_L` bit 0-2, 4-6):
https://github.com/GValiente/butano/blob/5253c0444b64ef85655252b871f1c440aba4aa16/butano/hw/3rd_party/gbt-player/src/gbt_player.c#L558-L559

What I meant is that the DMG Master Volume, relative to the Direct Sound Volume.
which is set via `SOUNDCNT_H` (bit 0-1), but in both GBT & VGM Player, it's untouched.
So the resulting DMG Master Volume is `25%`, which is really small compared to Direct Sound Master volume.

**Comment by GValiente** [comment]
https://github.com/GValiente/butano/commit/c40fa7993378b66261a48a0499616ea104fb4131 allows to change DMG music master volume.

**Comment by copyrat90** [comment]
Thanks!  That surely helps.
Also, it would be better to mention [in the Docs](https://gvaliente.github.io/butano/import.html#import_dmg_music) about this:
> The default DMG master volume is set to `25% (Quarter)`.
> If it sounds too quiet for you, you can change it via `bn::dmg_music::set_master_volume(..)`.

Something like above.

**Comment by GValiente** [comment]
Done, thanks.
