### ISSUE TITLE
"VgmIntrVblank failed" when pausing VGM music at the end of the song

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#57]
Unfortunately, this is NOT fixed in the https://github.com/GValiente/butano/commit/228b5037f06d787e66cd29daa6d24c3276c1ed65.
![vgm_intr_vblank_failed](https://github.com/GValiente/butano/assets/34793045/52a2d6aa-0c58-4da4-bb61-935af019ab5d)

Here's the patch that reproduces this issue.
[vgm_intr_vblank_failed_2.zip](https://github.com/GValiente/butano/files/13200089/vgm_intr_vblank_failed_2.zip)

**Comment by GValiente** [comment]
Thanks for the issue!

With [this commit](https://github.com/GValiente/butano/commit/5253c0444b64ef85655252b871f1c440aba4aa16), this test and the previous one should be fixed.

**Comment by copyrat90** [comment]
Yeah, it seems that it's fixed now.  Thanks!
