### ISSUE TITLE
Setting palette ID erroneously adjusting adjacent cell's tile_index

### ISSUE THREAD

**Issue by 6TELOIV** [GValiente/butano#58]
Attached is a minimum reproducible example of what is happening. In the example, you'd expect the tiles to cycle blue -> yellow -> green -> red, but on yellow and green tiles erroneously set their neighbor to 1 more than what they are (tile 1, or blank, in this case)

![image](https://github.com/GValiente/butano/assets/6667660/3e652e44-f077-4f6b-b8b9-186f09f93220)

[testing_palette_swap.zip](https://github.com/GValiente/butano/files/13655647/testing_palette_swap.zip)

**Comment by GValiente** [comment]
All palettes had only one slot (16 colors), so thanks to palette offset it was never going to work.

It works with a single palette with four slots (64 colors).

You don't need to deal with palette offset, by the way. 
Butano does it for you.

Fixed example: [testing_palette_swap_fixed.zip](https://github.com/GValiente/butano/files/13657198/testing_palette_swap_fixed.zip)

**Comment by 6TELOIV** [comment]
Ah, looks like it was user error in that case! Thank you for the help. Would it be possible to convert this into an example? AFAIK, this 64 color 4bpp palette isn't used in the existing examples
