### ISSUE TITLE
[Request] Configurable precision for fixed_point.

### ISSUE THREAD

**Issue by alope107** [GValiente/butano#59]
Currently, you can use `fixed_t<Precision>` to set the number of bits to be used for the fractional part of a "poor man's float." There is a an alias `fixed` for `fixed_t<12>`.

There are other classes that would benefit from a configurable precision, most notably `fixed_point`. This 2D pair holds two `fixed` members. However, this is locked at the default 12 bits of fractional precision. It would be nice to instead have a `fixed_point_t<Precision>`, and have `fixed_point` be an alias for `fixed_point_t<12>`. This would allow anyone wanting a different precision to use the underlying `fixed_point_t`.

I would be happy to give implementing this a try if desired, though I am somewhat new to C++ and my PR would likely need a fair amount of feedback.

Alternatively, is there some simpler way that I'm missing to do this? Thanks!

**Comment by GValiente** [comment]
Added :)
https://github.com/GValiente/butano/commit/f33519c20db4bbf409e36e31802bc209e30c6816

**Comment by alope107** [comment]
Wow, that was fast! Thank you!
