### ISSUE TITLE
No Japanese support

### ISSUE THREAD

**Issue by dmitsuki** [GValiente/butano#6]
It seems as though you cannot use the text classes to render Japanese text, am I correct in assuming this?

**Comment by GValiente** [comment]
[bn::sprite_font](https://gvaliente.github.io/butano/classbn_1_1sprite__font.html) supports UTF-8 characters, it should be enough for japanese text support.

**Comment by dmitsuki** [comment]
That's what I thought, maybe it is a problem inputting the characters on my
end in the text editor, will test tomorrow

**Comment by GValiente** [comment]
If it helps, in this file additional UTF-8 characters are setup: https://github.com/GValiente/butano/blob/357c4f1f02c9b07bf5d70546917e7ed91cbb5222/common/include/variable_8x16_sprite_font.h#L12

**Comment by dmitsuki** [comment]
Yeah sorry for the late reply. I realized that just supporting UTF-8 wasn't enough, I actually needed a bitmap that had all the Japanese characters and to set it up. Sorry about that.
