### ISSUE TITLE
Butano CMake Toolchain?

### ISSUE THREAD

**Issue by tfinnegan937** [GValiente/butano#60]
Hello Butano development team! Sorry to open an issue on this, but I didn't see contact information for any of the developers.

I think Butano is a fantastic project, but as a regular user of CMake over Makefiles, I find myself desperately wanting a CMake equivalent for the toolchain. 

Is there any interest in this at all within the Butano team? The current makefile toolchain seems to be quite straightforward, so I was thinking that I could take some time, write up some basic CMake project structure, and then open a PR.

I'd rather not take the time to do this if the Butano team is not interested, however. I'd envision this as an either/or sort of thing -- We would leave the Makefiles as-is, and then for those that use CMake extensively for project management we could provide the CMake bindings.

Theoretically Butano could work with CMake as-is if inserted as an external project, but if I'm being entirely honest that's not particularly pretty.

But either way, if this isn't something that you would like to integrate, feel free to tell me to buzz off.

**Comment by GValiente** [comment]
Hi!

[gba-toolchain](https://github.com/felixjones/gba-toolchain) already allows to work with Butano using CMake.

I'm not currently interested in replacing the current makefiles with CMake, or adding CMake bindings.
