### ISSUE TITLE
Makefile error message about missing DEVKITARM/WONDERFUL_TOOLCHAIN is not displayed correctly

### ISSUE THREAD

**Issue by LunarLambda** [GValiente/butano#61]
[Line 10 in butano.mak](https://github.com/GValiente/butano/blob/master/butano/butano.mak#L10) should not be indented, or be indented using spaces.

When Make encounters a tab-indented `$(...)`, it tries to parse it as part of a recipe, resulting in the error message `recipe commences before first target` being shown, instead of the message about the missing environment variables.

Only "directives" like conditionals, includes, and variable assignments can be indented (with tab, indenting with spaces is fine outside of recipes). See [GNU Make Error Messages](https://www.gnu.org/software/make/manual/html_node/Error-Messages.html).

**Comment by GValiente** [comment]
Fixed, I hope: https://github.com/GValiente/butano/commit/343c48f479d77fdeb07d07f1ec1eaa6a9b3ae105

Thanks for the issue.

**Comment by GValiente** [comment]
I'll close this issue.

Please feel free to create a new one if you need it.
