### ISSUE TITLE
I can't create gba file using make on Debian

### ISSUE THREAD

**Issue by fortnite2015** [GValiente/butano#65]
Whenever I try to change directory to varooom 3d and use `sudo make -j8` I get the error

/home/mystuff/butano/butano/butano.mak:10:  *** "DEVKITARM and WONDERFUL_TOOLCHAIN not found".  Stop

**Comment by copyrat90** [comment]
Have you been following [Getting started guide](https://gvaliente.github.io/butano/getting_started.html) step by step?
If so, I believe you have to set the `DEVKITPRO` and `DEVKITARM` environment variables manually.

**Comment by GValiente** [comment]
> If so, I believe you have to set the `DEVKITPRO` and `DEVKITARM` environment variables manually.

At least I've never needed to do that (on Windows and Ubuntu).

**Comment by fortnite2015** [comment]
I figured it out and it started to build now. I just overlooked a step in the guide.
 If you have an Ubuntu/Debian based system with python3 instead of python, you can:

Specify python3 as the Python interpreter path in the Makefile of the project you are trying to build.
Install python-is-python3: sudo apt-get install python-is-python3.

**Comment by GValiente** [comment]
Nice.

Can you close the issue if it has been resolved, please?
