### ISSUE TITLE
[Request] Support wireless adapter for `bn::link` API

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#66]
Looks like [LinkUniversal.hpp](https://github.com/afska/gba-link-connection/blob/master/lib/LinkUniversal.hpp) has been added to [gba-link-connection](https://github.com/afska/gba-link-connection), which you can use to support both link cable and the wireless adapter.
It would be nice to update to this instead of current [LinkConnection.h](https://github.com/GValiente/butano/blob/91a17a89ffdbf4ff17d2ae7358cdfe9b7886f0e6/butano/hw/3rd_party/gba-link-connection/include/LinkConnection.h)

**Comment by GValiente** [comment]
Since I don't have multiple wireless adapters for testing and they're too niche to be interesting to me, *for now* I'm not going to support them.

What I'm interested in is to know if it is possible to use modern LinkConnection with Butano without having to modify internal Butano code. Have you tried?

**Comment by copyrat90** [comment]
`LinkConnection.h` has been renamed to [LinkCable.hpp](https://github.com/afska/gba-link-connection/blob/master/lib/LinkCable.hpp), and API has been changed, so we need to change some code in `bn_hw_link.cpp`.
I haven't done this myself.

In my opinion, if you decide to put effort to accommodate the API change of the new `LinkCable.hpp`, it would be better to update it to `LinkUniversal.hpp` instead.

**Comment by GValiente** [comment]
I mean using modern LinkConnection without touching existing bn::link implementation.

**Comment by copyrat90** [comment]
No, I haven't tried that either.

**Comment by GValiente** [comment]
https://github.com/GValiente/butano/commit/ddcf441ad0d1cb643580a7299ff0c93b1238b4fa should allow to use the latest version of LinkConnection without changing current implementation.

**Comment by copyrat90** [comment]
I just confirmed that you can use newer `gba-link-connection` sources without editing Butano source.
Although you need to override some ISRs via `bn::hw::irq::set_isr()`:
```cpp
linkUniversal = /* ... */ ;

bn::memory::set_dma_enabled(false);
bn::hw::irq::set_isr(bn::hw::irq::id::SERIAL, LINK_UNIVERSAL_ISR_SERIAL);
bn::hw::irq::set_isr(bn::hw::irq::id::TIMER1, LINK_UNIVERSAL_ISR_TIMER);
bn::core::set_vblank_callback(LINK_UNIVERSAL_ISR_VBLANK);

bn::hw::irq::enable(bn::hw::irq::id::SERIAL);
bn::hw::irq::enable(bn::hw::irq::id::TIMER1);
linkUniversal->activate();
```
