### ISSUE TITLE
150bpm s3m requirement?

### ISSUE THREAD

**Issue by benwiley4000** [GValiente/butano#70]
I am interested in using Butano to create a PCM audio player, so I'm using the suggested program (https://github.com/Fralacticus/gba-wav-to-s3m-converter) to convert from .wav to .s3m. By default this uses 5 second intervals and a tempo of 128bpm I guess.  I found that I can tell it to split in 10 second intervals instead, for example, and use a 64bpm tempo.

But I can only set integer intervals, and Butano is complaining when I try to run "make" after copying in my s3m file, saying it has to be 150bpm. In order to have this I would need 4.26666666667 second intervals, but I can't use this mentioned program for this, because it expects an integer.

I guess I could learn a bit more about module formats and write my own converter with some scripting. But I'm wondering what this 150bpm requirement is for, and if you have any other suggested methods for converting WAV to some playable module format.

**Comment by GValiente** [comment]
Sorry, but I don't know what this 150bpm requirement is for, and I don't have any other suggested methods for converting WAV to some playable module format.

Maybe you should ask gba-wav-to-s3m-converter author instead :)

**Comment by benwiley4000** [comment]
I was assuming 150bpm was a limit imposed by Butano since it's here in the source code: https://github.com/GValiente/butano/blob/d91a17a27fc605865626ea012071c903f49c0aae/butano/tools/s3m2gbt/s3m2gbt.py#L193

Is it a GBA system requirement?

**Comment by GValiente** [comment]
It seems you're importing your s3m file as [DMG music](https://gvaliente.github.io/butano/import.html#import_dmg_music) instead of [Direct Sound music](https://gvaliente.github.io/butano/import.html#import_direct_sound_music).

**Comment by benwiley4000** [comment]
Indeed that was my mistake, I'd read the documentation and followed directions for Direct Sound yet somehow ended up dragging my file into the dmg folder. Thanks for the course correction!
