### ISSUE TITLE
fixed::division and fixed::multiplication work incorrect in some cases

### ISSUE THREAD

**Issue by UnickSoft** [GValiente/butano#73]
Hi!
I was working on geometric calculation using bn::fixed and faced with "Division by zero" error. I dig deeper and found optimized branch of fixed::division and fixed::multiplication works incorrectly. Under optimized branches I consider these:
```
        if constexpr(Precision % 2 == 0)
        {
            int data = _data / half_scale();
            int other_data = other._data / half_scale();
            return from_data(data * other_data);
        }
```
```
        if constexpr(Precision % 2 == 0)
        {
            int data = _data * half_scale();
            int other_data = other._data / half_scale();
            return from_data(data / other_data);
        }
```
If other is too small (for example 0.0048) other_data will be 0. For devision it is fatal error "Division by zero". For multiplication it returns wrong result and it is hard to find where is mistake. For me self I've just removed this and use safe_* methods instead of. Maybe you need to make the same chanes in engine, because I spent several hours to find where is the problem and some one also can faced with this problem.

**Comment by UnickSoft** [comment]
Yes, this is true. But I didn't know about it and I just used operators *, /. Maybe you may add assert or more tricky condition to call optimized version when it possible and other cases call non-optimized.

By the way did you profile optimized version vs non-optimized? Maybe you have some number, because performance also importan for me.

**Comment by GValiente** [comment]
Sorry, but I don't know what assert or more tricky condition should I add to call one version or the other without reducing performance (and breaking compatibilty with older releases).

If you know what to add/change, I suggest using your own bn::fixed derived class and overloading * and / operators.

**Comment by UnickSoft** [comment]
Thanks.
