### ISSUE TITLE
Function for Updating Sprite Positions in Mode 7

### ISSUE THREAD

**Issue by player022** [GValiente/butano#74]
This is a request for help rather than a question. I achieved very good results with Mode 7 in the example, but I still cannot understand the logic behind the code. Therefore, when I wrote the sprite position update function based on my understanding, I encountered significant problems, and the sprite's position never met the expected results. I have no other options, so I'm asking for help here. I'm sorry for wasting your time.

**Comment by GValiente** [comment]
Here's a great tutorial about displaying 3d sprites with a "mode 7" setup: https://gbadev.net/tonc/mode7ex.html

And here's a port of the tutorial to Butano: https://github.com/GValiente/butano/pull/29

**Comment by player022** [comment]
Okay, I will read these carefully. Thank you for your reply.
