### ISSUE TITLE
Documentation: EWRAM macro

### ISSUE THREAD

**Issue by d9k** [GValiente/butano#79]
1) Can't understand the difference between `BN_DATA_EWRAM` and `BN_EWRAM_BSS_SECTION`.

2) Can't declare EWRAM variable inside the function:

```cpp
int main()
    BN_DATA_EWRAM int test;
```

I get error :rotating_light:  `attributes are not permitted in a function definitionC/C++(1113)`

3) How to dynamically allocate/deallocate EWRAM inside function properly? For something like `char *` for example.

**Comment by GValiente** [comment]
`BN_DATA_EWRAM` is for initialized data in EWRAM (whay you should use by default) and `BN_DATA_EWRAM_BSS` is for uninitialized data in EWRAM.

The [FAQ](https://gvaliente.github.io/butano/faq.html) explains how to allocate EWRAM inside a function.

**Comment by d9k** [comment]
@GValiente, documentation says:

> Allocate memory in the heap, since it is placed in EWRAM.

Does it mean `char *my_string` initialization always automatically happen in EWRAM, no macro prefix needed?

**Comment by GValiente** [comment]
No, in that case `"my string value"` should be stored in ROM. You're not using the heap in that sentence.

**Comment by d9k** [comment]
@GValiente, ok, in this case:

```cpp
    int *numbers;
    int c = 10;

    numbers = new int[c];

    for (int i = 0; i < c; i++) {
        numbers[i] = i*i;
    }

    BN_LOG("numbers[7]: ", numbers[7]);
```

Is `numbers` array stored in EWRAM?

**Comment by GValiente** [comment]
Yes, it should be stored in EWRAM.

You can log the `numbers` pointer and check if the address is in the on-board work RAM (EWRAM) range: 
https://problemkaputt.de/gbatek.htm#gbamemorymap

**Comment by d9k** [comment]
@GValiente, thanks a lot!

**Comment by d9k** [comment]
@GValiente, what about `BN_EWRAM_BSS_SECTION`? What is BSS section and when this macro can be used?

**Comment by GValiente** [comment]
https://en.wikipedia.org/wiki/.bss

Since the original issue was resolved, I'll close the issue.

**Comment by d9k** [comment]
@GValiente, thanks for the answers but I suggest improving the documentation. It would be very helpful for C++ novices like me. Probably link to example in repo with allocating array heap and asserting the address is in EWRAM range.
