### ISSUE TITLE
Can't create bn::optional<T> instance when T contains const member variable

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#9]
If I understand correctly, `bn::optional<T>::emplace()` is the only option to create a `bn::optional<T>` object which contains actual value, when `T` contains const member variable(s).
`std::optional<T>::emplace()` supports this, but `bn::optional<T>::emplace()` doesn't.
Because `bn::optional<T>::emplace()` uses `operator=` internally, but `T` can't have assignment operators, as it has const member variable(s).

## bn::optional
```cpp
#include "bn_core.h"
#include "bn_log.h"
#include "bn_optional.h"

class Test
{
    const int num_;
public:
    Test(int num) : num_(num) {}
    int GetNum() const { return num_; }
};

int main()
{
    bn::core::init();

    bn::optional<Test> a;
    // error: use of deleted function 'Test& Test::operator=(Test&&)'
    a.emplace(42);
    BN_LOG(a->GetNum());

    while (true)
        bn::core::update();
}
```

## std::optional
```cpp
#include <iostream>
#include <optional>

class Test
{
    const int num_;
public:
    Test(int num) : num_(num) {}
    int GetNum() const { return num_; }
};

int main()
{
    std::optional<Test> a;
    // no issue
    a.emplace(42);
    std::cout << a->GetNum();
    return 0;
}
```

**Comment by GValiente** [comment]
Please check the latest commit, I think it is fixed now.

**Comment by copyrat90** [comment]
It is fixed now.
Thank you for your quick action.
